[profile.default]
src = "src"
out = "out"
libs = ["lib", "dependencies"]

[dependencies]
smartcontractkit-chainlink-evm = "1.5.0"
solady = "0.1.26"

[rpc_endpoints]
mainnet = "https://rpc.flashbots.net"

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
